# fly.toml app configuration file generated for parkers-smartbrain-api on 2024-01-15T18:08:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "parkers-smartbrain-api"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
